[package]
name = "ahci"
version = "0.1.0"
authors = ["Gerd Zellweger <mail@gerdzellweger.com>"]

[dependencies]
uio = "0.1.*"
mmap = "*"
driverkit = { path = "../rust-driverkit" }

[[bin]]
name = "ahci"
path = "src/bin/ahci.rs"
